spring:
  datasource:
    url: jdbc:mysql://10.157.74.18:3309/epg?allowLoadLocalInfile=true
    username: study
    password: ${EPG_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: com.mysql.jdbc.Driver
  
  web:
    resources:
      static-locations: classpath:/static/
      cache-period: 0
        
server:
  port: 8282

logging:
  level:
    org.springframework.web: DEBUG
    com.example.tvschedule: DEBUG
    org.springframework.jdbc: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%21.21thread] --- %cyan([%32.32logger{39}]): [%16X{messageId}] %msg%n"